# Custom Language File for Launcher Customizer

[ejs.app]
title = "MicroVision Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@bryan_drouet2"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "https://microvision-modpack.bryan.ovh"

[ejs.welcome]
welcomeHeader = "BIENVENUE À MICROVISION"
welcomeDescription = "MicroVision Valkyria 2026 est un modpack Minecraft 1.20.1 complet comprenant plus de 135 mods soigneusement sélectionnés. Découvrez des contenus innovants, des défis captivants et une expérience de jeu unique. Préparez-vous à une aventure extraordinaire dans un monde transformé par la technologie et la magie."
welcomeDescCTA = "Vous êtes à quelques clics de l'aventure."
