[ejs.landing]
updateAvailableTooltip = "Actualización disponible"
usernamePlaceholder = "Nombre de usuario"
usernameEditButton = "Editar"
settingsTooltip = "Configuración"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "DESCONECTADO"
mojangStatus = "ESTADO DE MOJANG"
mojangStatusTooltipTitle = "Servicios"
mojangStatusNETitle = "No&nbsp;esencial"
newsButton = "NOTICIAS"
launchButton = "JUGAR"
launchButtonPlaceholder = "&#8226; Ningún servidor seleccionado"
launchDetails = "Por favor espere.."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Verificando noticias.."
newsErrorFailedSpan = "Error al cargar noticias"
newsErrorRetryButton = "Reintentar"
newsErrorNoneSpan = "Sin noticias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "INICIO DE SESIÓN EN MINECRAFT"
loginEmailError = "* Valor inválido"
loginEmailPlaceholder = "CORREO ELECTRÓNICO O NOMBRE DE USUARIO"
loginPasswordError = "* Requerido"
loginPasswordPlaceholder = "CONTRASEÑA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "¿olvidaste la contraseña?"
loginRememberMeText = "¿recuérdame?"
loginButtonText = "INICIAR SESIÓN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "¿Necesitas una cuenta?"
loginPasswordDisclaimer1 = "Tu contraseña se envía directamente a Mojang y nunca se guarda."
loginPasswordDisclaimer2 = "{appName} no está afiliado con Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opciones de inicio de sesión"
loginWithMicrosoft = "Iniciar sesión con Microsoft"
loginWithMojang = "Iniciar sesión con Mojang"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores disponibles"
serverSelectConfirm = "Seleccionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Seleccionar una cuenta"
accountSelectConfirm = "Seleccionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configuración"
navAccount = "Cuenta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Acerca de"
navUpdates = "Actualizaciones"
navDone = "Hecho"
tabAccountHeaderText = "Configuración de cuenta"
tabAccountHeaderDesc = "Agregue nuevas cuentas o administre las existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Agregar cuenta de Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Agregar cuenta de Mojang"
minecraftTabHeaderText = "Configuración de Minecraft"
minecraftTabHeaderDesc = "Opciones relacionadas con el lanzamiento del juego."
gameResolutionTitle = "Resolución del juego"
launchFullscreenTitle = "Lanzar en pantalla completa."
autoConnectTitle = "Conectarse automáticamente al servidor al iniciar."
launchDetachedTitle = "Lanzar el proceso del juego independientemente del launcher."
launchDetachedDesc = "Si el juego no está independiente, cerrar el launcher también cerrará el juego."
tabModsHeaderText = "Configuración de mods"
tabModsHeaderDesc = "Habilitar o deshabilitar mods."
switchServerButton = "Cambiar"
requiredMods = "Mods requeridos"
optionalMods = "Mods opcionales"
dropinMods = "Mods complementarios"
addMods = "Agregar mods"
dropinRefreshNote = "(F5 para actualizar)"
shaderpacks = "Paquetes de shaders"
shaderpackDesc = "Habilite o deshabilite los shaders. Tenga en cuenta que los shaders solo funcionarán correctamente en configuraciones potentes. Puede agregar paquetes personalizados aquí."
selectShaderpack = "Seleccionar paquete de shaders"
tabJavaHeaderText = "Configuración de Java"
tabJavaHeaderDesc = "Administre la configuración de Java (avanzado)."
memoryTitle = "Memoria"
maxRAM = "RAM máxima"
minRAM = "RAM mínima"
memoryDesc = "La RAM mínima recomendada es de 3 gigabytes. Establecer los valores mínimo y máximo al mismo valor puede reducir el lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Ejecutable de Java"
javaExecSelDialogTitle = "Seleccionar ejecutable de Java"
javaExecSelButtonText = "Elegir archivo"
javaExecDesc = "El ejecutable de Java se valida antes de iniciar el juego."
javaPathDesc = "La ruta debe terminar con <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opciones JVM adicionales"
jvmOptsDesc = "Opciones a proporcionar a la JVM en tiempo de ejecución. <em>-Xms</em> y <em>-Xmx</em> no deben incluirse."
launcherTabHeaderText = "Configuración del launcher"
launcherTabHeaderDesc = "Opciones relacionadas con el launcher."
languageTitle = "Idioma del launcher"
languageDesc = "Selecciona el idioma de la interfaz del launcher."
languageFrench = "Français"
languageSpanish = "Español"
languageEnglish = "English"
allowPrereleaseTitle = "Permitir actualizaciones de preversión."
allowPrereleaseDesc = "Las preversiones incluyen nuevas funciones que pueden no haber sido completamente probadas o integradas.<br>Esto siempre será verdadero si usa una versión de preversión."
dataDirectoryTitle = "Directorio de datos"
selectDataDirectory = "Seleccionar directorio de datos"
chooseFolder = "Elegir carpeta"
dataDirectoryDesc = "Todos los archivos del juego e instalaciones locales de Java se almacenarán en el directorio de datos.<br>Las capturas de pantalla y guardos se almacenan en la carpeta de instancia para la configuración del servidor correspondiente."
aboutTabHeaderText = "Acerca de"
aboutTabHeaderDesc = "Ver información y notas de versión para la versión actual."
aboutTitle = "{appName}"
stableRelease = "Versión estable"
versionText = "Versión "
sourceGithub = "Fuente"
support = "Soporte"
devToolsConsole = "Consola DevTools"
releaseNotes = "Notas de versión"
changelog = "Historial de cambios"
noReleaseNotes = "Sin notas de versión"
viewReleaseNotes = "Ver notas de versión"
launcherUpdatesHeaderText = "Actualizaciones del launcher"
launcherUpdatesHeaderDesc = "Descargue, instale y revise las actualizaciones del launcher."
checkForUpdates = "Verificar actualizaciones"
whatsNew = "Novedades"
updateReleaseNotes = "Notas de versión de la actualización"

[ejs.waiting]
waitingText = "En espera de Microsoft.."

[ejs.welcome]
welcomeHeader = "BIENVENIDO A MICROVISION"
welcomeDescription = "MicroVision Valkyria 2026 es un paquete de modificaciones completo de Minecraft 1.20.1 que incluye más de 135 mods cuidadosamente seleccionados. Descubra contenidos innovadores, desafíos cautivadores y una experiencia de juego única. Prepárate para una aventura extraordinaria en un mundo transformado por la tecnología y la magia."
welcomeDescCTA = "Estás a pocos clics de la aventura."
continueButton = "CONTINUAR"

[js.discord]
waiting = "En espera del cliente.."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Inicio de sesión de Microsoft"
microsoftLogoutTitle = "Cierre de sesión de Microsoft"

[js.login]
login = "INICIAR SESIÓN"
loggingIn = "INICIANDO SESIÓN"
success = "ÉXITO"
tryAgain = "Reintentar"

[js.login.error]
invalidValue = "* Valor inválido"
requiredValue = "* Requerido"
