[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;essentiel"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités.."
newsErrorFailedSpan = "Impossible de charger les actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Pas d'actualités"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "ADRESSE E-MAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Obligatoire"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n'est jamais enregistré."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Connexion avec Microsoft"
loginWithMojang = "Connexion avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter de nouveaux comptes ou gérer les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en mode plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur au lancement."
launchDetachedTitle = "Lancer le processus du jeu indépendamment du launcher."
launchDetachedDesc = "Si le jeu n'est pas indépendant, fermer le launcher fermera également le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods obligatoires"
optionalMods = "Mods optionnels"
dropinMods = "Mods à placer"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activez ou désactivez les shaders. Veuillez noter que les shaders ne fonctionneront correctement que sur des configurations puissantes. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner un pack de shaders"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "La RAM minimale recommandée est de 3 gigaoctets. Définir les valeurs minimale et maximale à la même valeur peut réduire les ralentissements."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'exécutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à fournir à la JVM lors de l'exécution. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être inclus."
launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options liées au launcher lui-même."
allowPrereleaseTitle = "Autoriser les mises à jour de préversion."
allowPrereleaseDesc = "Les préversions incluent de nouvelles fonctionnalités qui peuvent ne pas avoir été entièrement testées ou intégrées.<br>Ceci sera toujours vrai si vous utilisez une version de préversion."
dataDirectoryTitle = "Répertoire de données"
selectDataDirectory = "Sélectionner le répertoire de données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations locales de Java seront stockés dans le répertoire de données.<br>Les captures d'écran et les sauvegardes de mondes sont stockées dans le dossier d'instance pour la configuration de serveur correspondante."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Voir les informations et les notes de version pour la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Journal des modifications"
noReleaseNotes = "Pas de notes de version"
viewReleaseNotes = "Voir les notes de version"
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et consulter les mises à jour du launcher."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Quoi de neuf"
updateReleaseNotes = "Notes de version de la mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
welcomeHeader = "BIENVENUE À MICROVISION"
welcomeDescription = "MicroVision Valkyria 2026 est un modpack Minecraft 1.20.1 complet comprenant plus de 135 mods soigneusement sélectionnés. Découvrez des contenus innovants, des défis captivants et une expérience de jeu unique. Préparez-vous à une aventure extraordinaire dans un monde transformé par la technologie et la magie."
welcomeDescCTA = "Vous êtes à quelques clics de l'aventure."
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client.."
state = "Serveur: {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Obligatoire"
